### ISSUE TITLE
Add waveform generation

### ISSUE THREAD

**Issue by itskingori** [bbc/audio_waveform-ruby#1]
Are there any plans to somehow add the ability to generate audio waveform from Ruby. Maybe an wrapper for the audiowaveform C/C++ app..

**Comment by benbenedek** [comment]
+1 👍

**Comment by chrisn** [comment]
We don't have plans to add this, but contributions would be very welcome.

**Comment by marceloboeira** [comment]
@chrisn I will take a look, maybe I can work on a PR for that.
