### ISSUE TITLE
Filename 

### ISSUE THREAD

**Issue by BlazPerus** [bbc/audio_waveform-ruby#3]
Hello,

What parameter should be the **filename** and in what context does it exsist? Is there a way to put in the absolute path to a filename? 

`waveform = AudioWaveform::WaveformDataFile.new(filename: "test.dat")`

I have a sidekiq worker that gets a path to file and now i'd like to generate waveform data for that file.. But I don't know how to call the file. 

Ideally i'd like to put a path to the filename something like: 

`"/public/assets/<%= id.to_s %>/test.dat"`

Suggestions? Thanks!

**Comment by chrisn** [comment]
The `filename` parameter is the file system path to your `.dat` file, which must have already been created using [audiowaveform](https://github.com/bbc/audiowaveform). Once you have the `.dat` file, code such as the following should work to read the file:
```ruby
waveform = AudioWaveform::WaveformDataFile.new(filename: "/path/to/test.dat")
```
What error are you seeing?

**Comment by BlazPerus** [comment]
The path wasn't correct, had to put in the full path.

```
if Rails.env.development?
      file_to_transcode = file_path
      path_to_create_raw_file = File.join(Rails.public_path, "/tracks/" + id.to_s + "/raw.dat")
   elsif Rails.env.production?
      file_to_transcode = "/home/deploy/apps/MyAppFolder/current/" + file_path.to_s
      path_to_create_raw_file = "/home/deploy/apps/MyAppFolder/current/public/tracks/" + id.to_s +  "/raw.dat"
    end

waveform = AudioWaveform::WaveformDataFile.new(filename: path_to_create_raw_file)

```

This did the trick.
